SourceCode/EmployeeTracking.Admin/Controllers/AttendanceManagementController.cs
using EmployeeTracking.Core.Repositories;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EmployeeTracking.Admin.Filters;

namespace EmployeeTracking.Admin.Controllers
{
    public class AttendanceManagementController : Controller
    {
        private TrackAttendanceRepo _trackAttendanceRepo;
        public AttendanceManagementController()
        {
            _trackAttendanceRepo = new TrackAttendanceRepo();
        }

        // GET: AttendanceManagement
        [CheckLoginFilter]
        [RoleFilter(ActionName = "Attendance")]
        public ActionResult Index(int? page)
        {
            const int pageSize = 10;
            int pageNumber = (page ?? 1);
            var data = _trackAttendanceRepo.GetAllAttendance();
            return View(data.ToPagedList(pageNumber, pageSize));
        }
        [CheckLoginFilter]
        [RoleFilter(ActionName = "Attendance_ExportExcel")]
        public ActionResult ExportExcel()
        {
            var bin = _trackAttendanceRepo.GetExportTrackList();

            string fileName = Guid.NewGuid().ToString() + ".xlsx";
            return File(bin, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
    }
}

SourceCode/EmployeeTracking.Admin/Views/AttendanceManagement/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<EmployeeTracking.Data.ModelCustom.AttendanceManagerModel>
@using System.Configuration;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var lstRoles = (List<String>)Session["Roles"];
}

<h2>Quản lý điểm danh</h2>

<div class="row">
    <div class="col-xs-12">
        <a class="btn btn-sm btn-info" href="@Url.Action("ExportExcel", "AttendanceManagement")">Export Excel</a>
    </div>
</div>
<div class="row clearfix">
    <p></p>
</div>


<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-12">
                        <table class="table table-bordered table-striped table-hover">
                            <thead style="font-weight:bold;">
                                <tr>
                                    <td>.No</td>
                                    <td>Mã nhân viên</td>
                                    <td>Họ và Tên</td>
                                    <td>Ngày</td>
                                    <td>Giờ bắt đầu</td>
                                    <td>Giờ kết thúc</td>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.Index)</td>
                                        <td>@Html.DisplayFor(modelItem => item.EmployeeCode)</td>
                                        <td>@Html.DisplayFor(modelItem => item.EmployeeName)</td>
                                        <td>@Html.DisplayFor(modelItem => item.DateString)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Start)</td>
                                        <td>@Html.DisplayFor(modelItem => item.End)</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        @Html.PagedListPager(Model, page => Url.Action("Index", new
                       {
                           page = page
                       }), PagedListRenderOptions.PageNumbersOnly)
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>