SourceCode/EmployeeTracking.Admin/Controllers/ImageManagementController.cs
using EmployeeTracking.Admin.Filters;
using EmployeeTracking.Core;
using EmployeeTracking.Core.Repositories;
using EmployeeTracking.Core.Utils;
using EmployeeTracking.Core.Utils.JqueryDataTable;
using EmployeeTracking.Data.ModelCustom;
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using EmployeeTracking.Admin.Controllers;
using System.IO.Compression;

namespace EmployeeTracking.Controllers
{
    public class ImageManagementController : BasicController
    {
        private string rootMedia = @"" + WebConfigurationManager.AppSettings["rootMedia"];
        private string tempMedia = @"" + WebConfigurationManager.AppSettings["WebServerTempFolder"];
        //private string rootMedia = @"D:\test image";

        private ImageManagementRepo _imageManagementRepo;
        private MediaTypeRepo _mediaTypeRepo;
        private StoreRepo _StoreRepo;
        private TrackDetailRepo _trackDetailRepo;
        private EmployeeRepo _employeeRepo;
        private TrackRepo _tr;

        public ImageManagementController()
        {
            _imageManagementRepo = new ImageManagementRepo();
            _mediaTypeRepo = new MediaTypeRepo();
            _StoreRepo = new StoreRepo();
            _trackDetailRepo = new TrackDetailRepo();
            _employeeRepo = new EmployeeRepo();
            _tr = new TrackRepo();
        }


        // GET: ImageManagement
        [CheckLoginFilter]
        [RoleFilter(ActionName = "ImageManager")]
        public ActionResult Index()
        {
            var account = (Data.Database.user)Session["Account"];
            string userId = account.Id.ToString();
            string tempFolderPath = Server.MapPath("~/temp/" + userId);

            if (Directory.Exists(tempFolderPath))
            {
                try
                {
                    Directory.Delete(tempFolderPath, true);
                }
                catch { }
            }

            ViewBag.employee = _employeeRepo.ListEmployeeByUserToShowCombobox(account.Id);
            //ViewBag.store = _StoreRepo.GetListStoreToShowOnCombobox();
            ViewBag.region = _StoreRepo.GetListRegionToShowOnCombobox();
            ViewBag.province = _StoreRepo.GetListProvinceToShowOnCombobox();

            return View();
        }

        /// <summary>
        /// Group form
        /// Post method
        /// </summary>
        /// <param name="requestData"></param>
        /// <returns>DataTableResponse<GroupModel></returns>
        [HttpPost]
        [CheckLoginFilter]
        //[RoleFilter(ActionName = "ImageManager_Search")]
        public JsonResult Index(CustomDataTableRequestHelper requestData)
        {
            var account = (Data.Database.user)Session["Account"];
            //try
            //{
            #region " [ Declaration ] "

            #endregion

            #region " [ Main processing ] "

            if (requestData.FromDate == null) // From date
            {
                requestData.FromDate = DateTime.Now.ToString("yyyy-MM-dd");
            }
            if (requestData.ToDate == null) // To date
            {
                requestData.ToDate = DateTime.Now.ToString("yyyy-MM-dd");
            }
            if (requestData.Region == null) // Region
            {
                requestData.Region = new List<string>();
            }
            if (requestData.Store == null) // Store
            {
                requestData.Store = new List<string>();
            }
            if (requestData.Employee == null) // Employee
            {
                requestData.Employee = new List<string>();
            }

            requestData.UserId = account.Id;
            // Process sorting column
            //requestData = requestData.SetOrderingColumnName();

            #endregion

            //Call to service
            Dictionary<string, object> _return = _imageManagementRepo.List(requestData);
            //
            if ((ResponseStatusCodeHelper)_return[DatatableCommonSetting.Response.STATUS] == ResponseStatusCodeHelper.OK)
            {
                DataTableResponse<ImageManagementViewModel> itemResponse = _return[DatatableCommonSetting.Response.DATA] as DataTableResponse<ImageManagementViewModel>;
                return this.Json(itemResponse, JsonRequestBehavior.AllowGet);
            }
            //
            return this.Json(new DataTableResponse<ImageManagementViewModel>(), JsonRequestBehavior.AllowGet);
            //}
            //catch (ServiceException serviceEx)
            //{
            //    throw serviceEx;
            //}
            //catch (DataAccessException accessEx)
            //{
            //    throw accessEx;
            //}
            //catch (Exception ex)
            //{
            //    throw new ControllerException(FILE_NAME, MethodInfo.GetCurrentMethod().Name, UserID, ex);
            //}
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">TrackSessionId</param>
        /// <returns></returns>
        [CheckLoginFilter]
        [RoleFilter(ActionName = "ImageManager_UpdateTrackSession")]
        public ActionResult EditTrackSession(string id)
        {
            var account = (Data.Database.user)Session["Account"];
            string userId = account.Id.ToString();
            string tempFolderPath = Server.MapPath("~/temp/" + userId);

            if (Directory.Exists(tempFolderPath))
            {
                Directory.Delete(tempFolderPath, true);
            }

            ViewBag.StoreInfo = _imageManagementRepo.GetStoreInfoByTrackSessionId(id);

            //ViewBag.StoreInfo = _imageManagementRepo.GetStoreInfoByTrackId(id);

            //ViewBag.POSM
            ViewBag.PosmType = _mediaTypeRepo.GetOnlyPOSM();

            var model = _imageManagementRepo.GetTrackDetailListByTrackSessionId(id);

            model.ForEach(f =>
            {
                f.TrackDetailImages.ToList().ForEach(_ =>
                {
                    _.Url = WebConfigurationManager.AppSettings["rootMediaURl"] + _.Url;
                });
            });
            ViewBag.TrackSessionsId = id;
            return PartialView("_EditTrackSession", model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">TrackId</param>
        /// <returns></returns>
        [CheckLoginFilter]
        public ActionResult ExpandTrack(string id)
        {
            var model = _imageManagementRepo.GetStoreInfoByTrackId(id);
            ViewBag.TrackSessionList = _imageManagementRepo.GetTrackSessionListByTrackId(id);
            ViewBag.PosmInfo = _imageManagementRepo.GetPOSMStatisticByTrackID(id);
            ViewBag.TrackId = id;
            return PartialView("_ExpandTrack", model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">TrackSessionId</param>
        /// <returns></returns>
        [CheckLoginFilter]
        public ActionResult TrackSessionCarousel(string id, string TrackIdForCarousel)
        {
            var model = _imageManagementRepo.GetTrackDetailListByTrackSessionId(id);
            model.ForEach(f =>
            {
                f.TrackDetailImages.ToList().ForEach(_ =>
                {
                    _.Url = WebConfigurationManager.AppSettings["rootMediaURl"] + _.Url;
                });
            });
            Response.Headers["trackSessionIdForCarousel"] = TrackIdForCarousel;
            ViewBag.TrackIdForCarousel = TrackIdForCarousel;
            return PartialView("_TrackSessionCarousel", model);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">TrackSessionId</param>
        /// <returns></returns>
        [CheckLoginFilter]
        public ActionResult DownloadImagePackage(string id)
        {
            var sessionList = _imageManagementRepo.GetTrackDetailListByTrackSessionId(id);

            using (MemoryStream ms = new MemoryStream())
            {
                using (var archive = new ZipArchive(ms, ZipArchiveMode.Create, true))
                {

                    foreach (var item in sessionList)
                    {
                        foreach (var image in item.TrackDetailImages)
                        {
                            try
                            {
                                var path = rootMedia + Path.Combine(image.Url, image.FileName);
                                byte[] file = System.IO.File.ReadAllBytes(path);

                                var zipArchiveEntry = archive.CreateEntry($"{item.MediaTypeName}\\{image.FileName}", CompressionLevel.Fastest);
                                using (var zipStream = zipArchiveEntry.Open()) zipStream.Write(file, 0, file.Length);
                            }
                            catch (Exception)
                            {
                            }
                        }
                    }
                }

                // TODO: đặt tên file
                return File(ms.ToArray(), "application/zip", "Archive.zip");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [CheckLoginFilter]
        public ActionResult ChangeDetailImage(ChangeDetailImageViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new MessageReturnModel
                {
                    IsSuccess = false,
                    Message = "Không tìm thấy id! Vui lòng tải lại trang."
                });
            }


SourceCode/EmployeeTracking.Admin/Controllers/LocationController.cs
using EmployeeTracking.Core.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EmployeeTracking.Admin.Filters;

namespace EmployeeTracking.Admin.Controllers
{
    public class LocationController : Controller
    {
        private ProvinceRepo _provinceRepo;
        private DistrictRepo _districtRepo;
        private WardRepo _wardRepo;

        public LocationController()
        {
            _provinceRepo = new ProvinceRepo();
            _districtRepo = new DistrictRepo();
            _wardRepo = new WardRepo();
        }

        // GET: Location
        //public ActionResult Index()
        //{
        //    return View();
        //}
        [CheckLoginFilter]
        public JsonResult GetProvinceSelect() 
        {
            var jsonData = _provinceRepo.GetAll();
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }
        [CheckLoginFilter]
        public JsonResult GetDistrictSelect(long provinceId)
        {

            var jsonData = _districtRepo.GetByProvinceId(provinceId);
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }
        [CheckLoginFilter]
        public JsonResult GetWardSelect(long districtId)
        {

            var jsonData = _wardRepo.GetByDistrictId(districtId);
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [CheckLoginFilter]
        public JsonResult GetAllStoreAllProvince()
        {
            return this.Json(_provinceRepo.CountStoreAllProvince(), JsonRequestBehavior.AllowGet);
        }
    }
}

SourceCode/EmployeeTracking.Admin/Views/ImageManagement/PopupDetail.cshtml
@model EmployeeTracking.Data.ModelCustom.TrackViewModel
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<div class="modal-content">
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "frmDetail" }))
    {
        @Html.ValidationSummary(true)
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Cập nhật thông tin cửa hàng</h4>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-xs-12">
                    @Html.HiddenFor(model => model.Id)
                    <div class="form-group">
                        <label class="control-label">Tên cửa hàng</label>
                        @Html.TextBoxFor(model => model.MasterStoreName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MasterStoreName, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label class="control-label">Loại hình cửa hàng</label>
                        @(Html.DropDownListFor(model => model.StoreType, new SelectList(Enumerable.Empty<SelectListItem>()), new { @class = "form-control" }))
                        @Html.ValidationMessageFor(model => model.StoreType, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label class="control-label">Số nhà</label>
                        @Html.TextBoxFor(model => model.HouseNumber, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.HouseNumber, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label class="control-label">Số điện thoại</label>
                        @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label class="control-label">Tên đường</label>
                        @Html.TextBoxFor(model => model.StreetNames, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.StreetNames, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label class="control-label">Tỉnh/Thành Phố</label>
                        @(Html.DropDownListFor(model => model.ProvinceId, new SelectList(Enumerable.Empty<SelectListItem>()), new { @class = "form-control" }))
                        @Html.ValidationMessageFor(model => model.ProvinceId, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label class="control-label">Quận/Huyện</label>
                        @(Html.DropDownListFor(model => model.DistrictId, new SelectList(Enumerable.Empty<SelectListItem>()), new { @class = "form-control" }))
                        @Html.ValidationMessageFor(model => model.DistrictId, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label class="control-label">Phường/Xã</label>
                        @(Html.DropDownListFor(model => model.WardId, new SelectList(Enumerable.Empty<SelectListItem>()), new { @class = "form-control" }))
                        @Html.ValidationMessageFor(model => model.WardId, "", new { @class = "text-danger" })
                    </div>


                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            <button type="submit" class="btn btn-primary">Lưu lại</button>
        </div>
    }
</div>

<script>
    $(document).ready(function () {
        loadStoreType();
        loadProvince();
        provinceChange();
        districtChange();
        var form = $("#frmDetail");
        form.validate();
        //Lưu
        $("#frmDetail").submit(function (event) {
            event.preventDefault();
            if (form.valid()) { //nhập hợp lệ
                $.ajax({
                //url: '/ImageManagement/PostDetail',
                url: '@Url.Action("PostDetail", "ImageManagement")',
                type: "POST",
                data: $("#frmDetail").serialize(),
                success: function (data) {
                    if (data.IsSuccess) {
                        closePopUp();
                        $(digixCurrentRow).find('td.DigixName').html($('#MasterStoreName').val());
                        $(digixCurrentRow).find('td.DigixType').html($("#StoreType option:selected").text());
                        $(digixCurrentRow).find('td.DigixHouseNumber').html($('#HouseNumber').val());
                        $(digixCurrentRow).find('td.DigixPhone').html($('#PhoneNumber').val());
                        $(digixCurrentRow).find('td.DigixStreetName').html($('#StreetNames').val());
                        $(digixCurrentRow).find('td.DigixProvince').html($("#ProvinceId option:selected").text());
                        $(digixCurrentRow).find('td.DigixDistrict').html($("#DistrictId option:selected").text());
                        $(digixCurrentRow).find('td.DigixWard').html($("#WardId option:selected").text());
                    }
                    else {
                        openFunc.pushNotifyError(data.Message);
                    }
                }
            });
            }
        });

        $('#ProvinceId').change(function () {
            $('#DistrictId').empty();
            $('#WardId').empty();
            provinceChange();
        });

        $('#DistrictId').change(function () {
            $('#WardId').empty();
            districtChange();
        });
    });

    function loadStoreType() {
        $.ajax({
            //url: "/StoreManager/GetStoreTypeSelect",
            url: "@Url.Action("GetStoreTypeSelect", "StoreManager")",
            type: "GET",
            contentType: "application/json; charset=utf-8",
            datatype: JSON,
            success: function (result) {
                $("#StoreType").append($("<option></option>").val("").html("-- Chọn loại cửa hàng --"));
                $(result).each(function () {
                    if ("@Model.StoreType" != "" && this.Id == "@Model.StoreType")
                    {
                        $("#StoreType").append($("<option selected></option>").val(this.Id).html(this.Name));
                    }
                    else{
                        $("#StoreType").append($("<option></option>").val(this.Id).html(this.Name));
                    }
                });
            },
            error: function (data) { }
        });
    }

    function loadProvince() {
        $.ajax({
            //url: "/Location/GetProvinceSelect",
            url: "@Url.Action("GetProvinceSelect", "Location")",
            type: "GET",
            contentType: "application/json; charset=utf-8",
            datatype: JSON,
            success: function (result) {
                $("#ProvinceId").append($("<option></option>").val("").html("-- Chọn Tỉnh/Thành Phố --"));
                $(result).each(function () {
                    if ("@Model.ProvinceId" != "" && this.Id == "@Model.ProvinceId") {
                        $("#ProvinceId").append($("<option selected></option>").val(this.Id).html(this.Name));
                    }
                    else {
                        $("#ProvinceId").append($("<option></option>").val(this.Id).html(this.Name));
                    }
                });
            },
            error: function (data) { }
        });
    }

    function provinceChange() {
        if (($("#ProvinceId").val() == null || $("#ProvinceId").val() == "") && "@Model.ProvinceId" != "")
        {
            $.ajax({
                //url: "/Location/GetDistrictSelect",
                url: "@Url.Action("GetDistrictSelect", "Location")",
                type: "GET",
                contentType: "application/json; charset=utf-8",
                datatype: JSON,
                data: { provinceId: "@Model.ProvinceId" },
                success: function (result) {
                    $("#DistrictId").append($("<option></option>").val("").html("-- Chọn Quận/Huyện --"));
                    $(result).each(function () {
                        if ("@Model.DistrictId" != "" && this.Id == "@Model.DistrictId") {
                            $("#DistrictId").append($("<option selected></option>").val(this.Id).html(this.Name));
                        }
                        else {
                            $("#DistrictId").append($("<option></option>").val(this.Id).html(this.Name));
                        }
                    });
                },
                error: function (data) { }
            });
        }
        else if($("#ProvinceId").val() != null && $("#ProvinceId").val() != "")
        {
            $.ajax({
                //url: "/Location/GetDistrictSelect",
                url: "@Url.Action("GetDistrictSelect", "Location")",
                type: "GET",
                contentType: "application/json; charset=utf-8",
                datatype: JSON,
                data: { provinceId: $("#ProvinceId").val() },
                success: function (result) {
                    $("#DistrictId").append($("<option></option>").val("").html("-- Chọn Quận/Huyện --"));
                    $(result).each(function () {
                        if ("@Model.DistrictId" != "" && this.Id == "@Model.DistrictId") {
                            $("#DistrictId").append($("<option selected></option>").val(this.Id).html(this.Name));
                        }
                        else {
                            $("#DistrictId").append($("<option></option>").val(this.Id).html(this.Name));
                        }
                    });
                },
                error: function (data) { }
            });
        }
    }

    function districtChange() {
        if(($("#DistrictId").val() == null || $("#DistrictId").val() == "") && "@Model.DistrictId" != "")
        {
            $.ajax({
                //url: "/Location/GetWardSelect",
                url: "@Url.Action("GetWardSelect", "Location")",
                type: "GET",
                contentType: "application/json; charset=utf-8",
                datatype: JSON,
                data: { districtId: "@Model.DistrictId" },
                success: function (result) {
                    $("#WardId").append($("<option></option>").val("").html("-- Chọn Phường/Xã --"));
                    $(result).each(function () {
                        if ("@Model.WardId" != "" && this.Id == "@Model.WardId") {
                            $("#WardId").append($("<option selected></option>").val(this.Id).html(this.Name));
                        }
                        else {
                            $("#WardId").append($("<option></option>").val(this.Id).html(this.Name));
                        }
                    });
                },
                error: function (data) { }
            });
        }
        else if ($("#DistrictId").val() != null && $("#DistrictId").val() != "")
        {
            $.ajax({
                //url: "/Location/GetWardSelect",
                url: "@Url.Action("GetWardSelect", "Location")",
                type: "GET",
                contentType: "application/json; charset=utf-8",
                datatype: JSON,
                data: { districtId: $("#DistrictId").val() },
                success: function (result) {
                    $("#WardId").append($("<option></option>").val("").html("-- Chọn Phường/Xã --"));
                    $(result).each(function () {
                        if ("@Model.WardId" != "" && this.Id == "@Model.WardId") {
                            $("#WardId").append($("<option selected></option>").val(this.Id).html(this.Name));
                        }
                        else {
                            $("#WardId").append($("<option></option>").val(this.Id).html(this.Name));
                        }
                    });
                },
                error: function (data) { }
            });
        }
    }

    function closePopUp() {
        $('#myModalUpdateStore').modal('hide');
    }
</script>

SourceCode/EmployeeTracking.Admin/Views/ImageManagement/PopupUpdateDate.cshtml
@model EmployeeTracking.Data.ModelCustom.TrackViewModel
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<div class="modal-content">
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "frmDetail" }))
    {
        @Html.ValidationSummary(true)
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Cập nhật ngày thực hiện</h4>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-xs-12">
                    @Html.HiddenFor(model => model.Id)
                    <div class="form-group">
                        <label class="control-label">Ngày thực hiện</label>
                        @Html.TextBoxFor(model => model.Date, "{0:dd-MM-yyyy}", new { @class = "form-control", @type = "date", @Value = Model.Date.ToString("yyyy-MM-dd") })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            <button type="submit" class="btn btn-primary">Lưu lại</button>
        </div>
    }
</div>

<script>
    $(document).ready(function () {
        loadEmployee();
        var form = $("#frmDetail");
        form.validate();
        //Lưu
        $("#frmDetail").submit(function (event) {
            event.preventDefault();
            if (form.valid()) { //nhập hợp lệ
                $.ajax({
                    //url: '/ImageManagement/PosmUpdate',
                    url: '@Url.Action("UpdateDate", "ImageManagement")',
                    type: "POST",
                    data: $("#frmDetail").serialize(),
                    success: function (data) {
                        if (data.IsSuccess) {
                            openFunc.pushNotifySuccess("Cập nhật ngày thực hiện thành công!");
                            closePopUp();
                            table.ajax.reload();
                        }
                        else {
                            openFunc.pushNotifyError(data.Message);
                        }
                    }
                });
            }
        });

        function loadEmployee() {
            $.ajax({
                //url: "/Location/GetProvinceSelect",
                url: "@Url.Action("GetEmployeeSelect", "EmployeeManager")",
                type: "GET",
                contentType: "application/json; charset=utf-8",
                datatype: JSON,
                success: function (result) {
                    $("#EmployeeId").append($("<option></option>").val("").html("-- Chọn nhân viên --"));
                    $(result).each(function () {
                        if ("@Model.EmployeeId" != "" && this.Id == "@Model.EmployeeId") {
                            $("#EmployeeId").append($("<option selected></option>").val(this.Id).html(this.Name));
                        }
                        else {
                            $("#EmployeeId").append($("<option></option>").val(this.Id).html(this.Name));
                        }
                    });
                },
                error: function (data) { }
            });
        }
    });

    function closePopUp() {
        $('#myModalUpdateDate').modal('hide');
    }
</script>

SourceCode/EmployeeTracking.Admin/Views/ImageManagement/PopupUpdateStoreStatus.cshtml
@model EmployeeTracking.Data.ModelCustom.TrackViewModel
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<div class="modal-content">
    @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "frmDetail" }))
    {
        @Html.ValidationSummary(true)
        @Html.ValidationSummary(true)
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Cập nhật trạng thái cửa hàng</h4>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-xs-12">
                    @Html.HiddenFor(model => model.Id)
                    <div class="form-group">
                        <label class="control-label">Trạng thái cửa hàng</label>
                        @(Html.DropDownListFor(model => model.StoreStatus, new SelectList(new List<Object>()
                        {
                            new {value = true.ToString(), text="Thành công"},
                            new {value = false.ToString(), text="Không thành công"}
                        }, "value", "text"), new { @class = "form-control" }))
                        @Html.ValidationMessageFor(model => model.StoreStatus, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label class="control-label">Ghi chú</label>
                        @Html.TextAreaFor(model => model.Note, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                <button type="submit" class="btn btn-primary">Lưu lại</button>
            </div>
    }
</div>

<script>
    $(document).ready(function () {
        var form = $("#frmDetail");
        form.validate();
        //Lưu
        $("#frmDetail").submit(function (event) {
            event.preventDefault();
            if (form.valid()) { //nhập hợp lệ
                $.ajax({
                    //url: '/ImageManagement/PosmUpdate',
                    url: '@Url.Action("UpdateStoreStatus", "ImageManagement")',
                    type: "POST",
                    data: $("#frmDetail").serialize(),
                    success: function (data) {
                        if (data.IsSuccess) {
                            openFunc.pushNotifySuccess("Cập nhật thành công!");
                            closePopUp();
                            table.ajax.reload(null, false);
                        }
                        else {
                            openFunc.pushNotifyError(data.Message);
                        }
                    }
                });
            }
        });
    });

    function closePopUp() {
        $('#myModalUpdateStatus').modal('hide');
    }
</script>